openapi: 3.2.0
info:
  contact:
    email: contact@babylonlabs.io
  description: 'The Babylon Staking API offers information about the state of the Babylon BTC Staking system.

    Your access and use is governed by the API Access License linked to below.'
  license:
    name: API Access License
    url: https://docs.babylonlabs.io/assets/files/api-access-license.pdf
  title: Babylon Staking Prices API
  version: '2.0'
tags:
- name: Prices
paths:
  /v2/prices:
    get:
      description: Get latest prices for all available symbols
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.PublicResponse-map_string_float64'
        '400':
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_babylonlabs-io_staking-api-service_internal_shared_types.Error'
      tags:
      - Prices
      summary: Get prices
      x-summary-source: derived
      operationId: getV2Prices
      x-operation-id-source: derived
components:
  schemas:
    types.ErrorCode:
      enum:
      - INTERNAL_SERVICE_ERROR
      - VALIDATION_ERROR
      - NOT_FOUND
      - BAD_REQUEST
      - FORBIDDEN
      - UNPROCESSABLE_ENTITY
      - REQUEST_TIMEOUT
      type: string
      x-enum-varnames:
      - InternalServiceError
      - ValidationError
      - NotFound
      - BadRequest
      - Forbidden
      - UnprocessableEntity
      - RequestTimeout
    handler.PublicResponse-map_string_float64:
      properties:
        data:
          $ref: '#/components/schemas/map_string_float64'
        pagination:
          $ref: '#/components/schemas/handler.paginationResponse'
      type: object
    handler.paginationResponse:
      properties:
        next_key:
          type: string
      type: object
    github_com_babylonlabs-io_staking-api-service_internal_shared_types.Error:
      properties:
        err: {}
        errorCode:
          $ref: '#/components/schemas/types.ErrorCode'
        statusCode:
          type: integer
      type: object
    map_string_float64:
      additionalProperties:
        format: float64
        type: number
      type: object
